<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Company.ProjectName.Host</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Company.ProjectName.Application\Company.ProjectName.Application.csproj" />
    <ProjectReference Include="..\Company.ProjectName.Infraestructure\Company.ProjectName.Infraestructure.csproj" />
    <ProjectReference Include="..\Company.ProjectName.Shared\Company.ProjectName.Shared.csproj" />
  </ItemGroup>
</Project>
